---
abstract: 'A PoCo-IRC plugin which uploads'
author:
  - 'Hinrik Örn Sigurðsson <hinrik.sig@gmail.com>'
build_requires:
  ExtUtils::MakeMaker: 6.42
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 0.91'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: POE-Component-IRC-Plugin-ImageMirror
no_index:
  directory:
    - inc
    - t
    - xt
requires:
  HTTP::Cookies: 0
  HTTP::Headers: 0
  LWP::UserAgent::POE: 0
  List::MoreUtils: 0
  POE: 0
  POE::Component::IRC: 6.22
  POE::Component::IRC::Plugin::URI::Find: 0
  POE::Wheel::Run: 0
  URI::Title: 0
resources:
  Ratings: http://cpanratings.perl.org/d/POE-Component-IRC-Plugin-ImageMirror
  bugtracker: http://github.com/hinrik/poe-component-irc-plugin-imagemirror/issues
  homepage: http://search.cpan.org/dist/POE-Component-IRC-Plugin-ImageMirror
  license: http://dev.perl.org/licenses/
  repository: git://github.com/hinrik/poe-component-irc-plugin-imagemirror.git
version: 0.01
